// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if DECODER
namespace Iced.Intel.DecoderInternal {
	enum SerializedDataKind : byte {
		HandlerReference,
		ArrayReference,
	}
}
#endif
