// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if INSTR_INFO
namespace Blazed.Intel.InstructionInfoInternal {
	static partial class CpuidFeatureInternalData {
		static System.ReadOnlySpan<byte> GetGetCpuidFeaturesData() =>
			new byte[] {
				// Header
				0x00,
				0x00,
				0x01,
				0x80,
				0xFD,
				0x3F,
				0x00,
				0x00,
				0x10,
				0x70,
				0x00,
				0x00,
				0x08,
				0x00,
				0x00,
				0x08,
				0xC0,
				0x36,
				0x00,
				0x00,
				0x04,
				0x02,

				0x00,// INTEL8086
				0x01,// INTEL8086_ONLY
				0x02,// INTEL186
				0x03,// INTEL286
				0x04,// INTEL286_ONLY
				0x05,// INTEL386
				0x06,// INTEL386_ONLY
				0x07,// INTEL386_A0_ONLY
				0x08,// INTEL486
				0x09,// INTEL486_A_ONLY
				0x0A,// UMOV
				0x0B,// IA64
				0x0C,// X64
				0x0D,// ADX
				0x0E,// AES
				0x0F,// AVX
				0x0E, 0x0F,// AES_and_AVX
				0x10,// AVX2
				0x11,// AVX512_4FMAPS
				0x12,// AVX512_4VNNIW
				0x14,// AVX512_BITALG
				0x15,// AVX512_IFMA
				0x16,// AVX512_VBMI
				0x17,// AVX512_VBMI2
				0x18,// AVX512_VNNI
				0x1A,// AVX512_VPOPCNTDQ
				0x1B,// AVX512BW
				0x1C,// AVX512CD
				0x1D,// AVX512DQ
				0x1E,// AVX512ER
				0x1F,// AVX512F
				0x1F, 0x13,// AVX512F_and_AVX512_BF16
				0x1F, 0x19,// AVX512F_and_AVX512_VP2INTERSECT
				0x20,// AVX512PF
				0x21, 0x13,// AVX512VL_and_AVX512_BF16
				0x21, 0x14,// AVX512VL_and_AVX512_BITALG
				0x21, 0x15,// AVX512VL_and_AVX512_IFMA
				0x21, 0x16,// AVX512VL_and_AVX512_VBMI
				0x21, 0x17,// AVX512VL_and_AVX512_VBMI2
				0x21, 0x18,// AVX512VL_and_AVX512_VNNI
				0x21, 0x19,// AVX512VL_and_AVX512_VP2INTERSECT
				0x21, 0x1A,// AVX512VL_and_AVX512_VPOPCNTDQ
				0x21, 0x1B,// AVX512VL_and_AVX512BW
				0x21, 0x1C,// AVX512VL_and_AVX512CD
				0x21, 0x1D,// AVX512VL_and_AVX512DQ
				0x21, 0x1F,// AVX512VL_and_AVX512F
				0x22,// BMI1
				0x23,// BMI2
				0x24,// CET_IBT
				0x25,// CET_SS
				0x26,// CL1INVMB
				0x27,// CLDEMOTE
				0x28,// CLFLUSHOPT
				0x29,// CLFSH
				0x2A,// CLWB
				0x2B,// CLZERO
				0x2C,// CMOV
				0x2D,// CMPXCHG16B
				0x2E,// CPUID
				0x2F,// CX8
				0x30,// D3NOW
				0x31,// D3NOWEXT
				0x32,// OSS
				0x33,// ENQCMD
				0x34,// F16C
				0x35,// FMA
				0x36,// FMA4
				0x37,// FPU
				0x37, 0x2C,// FPU_and_CMOV
				0x38,// FPU287
				0x39,// FPU287XL_ONLY
				0x3A,// FPU387
				0x3B,// FPU387SL_ONLY
				0x3C,// FSGSBASE
				0x3D,// FXSR
				0x3E,// GFNI
				0x0F, 0x3E,// AVX_and_GFNI
				0x1F, 0x3E,// AVX512F_and_GFNI
				0x21, 0x3E,// AVX512VL_and_GFNI
				0x40,// HLE_or_RTM
				0x42,// INVPCID
				0x44,// LWP
				0x45,// LZCNT
				0x46,// MCOMMIT
				0x47,// MMX
				0x48,// MONITOR
				0x49,// MONITORX
				0x4A,// MOVBE
				0x4B,// MOVDIR64B
				0x4C,// MOVDIRI
				0x4D,// MPX
				0x4E,// MSR
				0x4F,// MULTIBYTENOP
				0x50,// PADLOCK_ACE
				0x51,// PADLOCK_PHE
				0x52,// PADLOCK_PMM
				0x53,// PADLOCK_RNG
				0x54,// PAUSE
				0x55,// PCLMULQDQ
				0x55, 0x0F,// PCLMULQDQ_and_AVX
				0x56,// PCOMMIT
				0x57,// PCONFIG
				0x58,// PKU
				0x59,// POPCNT
				0x5A,// PREFETCHW
				0x5B,// PREFETCHWT1
				0x5C,// PTWRITE
				0x5D,// RDPID
				0x5E,// RDPMC
				0x5F,// RDPRU
				0x60,// RDRAND
				0x61,// RDSEED
				0x62,// RDTSCP
				0x63,// RTM
				0x64,// SEP
				0x65,// SGX1
				0x66,// SHA
				0x68,// SKINIT_or_SVM
				0x69,// SMAP
				0x6A,// SMX
				0x6B,// SSE
				0x6C,// SSE2
				0x6D,// SSE3
				0x37, 0x6D,// FPU_and_SSE3
				0x6E,// SSE4_1
				0x6F,// SSE4_2
				0x70,// SSE4A
				0x71,// SSSE3
				0x72,// SVM
				0x73,// SEV_ES
				0x74,// SYSCALL
				0x75,// TBM
				0x76,// TSC
				0x77,// VAES
				0x1F, 0x77,// AVX512F_and_VAES
				0x21, 0x77,// AVX512VL_and_VAES
				0x78,// VMX
				0x78, 0x41,// VMX_and_INVEPT
				0x78, 0x43,// VMX_and_INVVPID
				0x79,// VPCLMULQDQ
				0x1F, 0x79,// AVX512F_and_VPCLMULQDQ
				0x21, 0x79,// AVX512VL_and_VPCLMULQDQ
				0x7A,// WAITPKG
				0x7B,// WBNOINVD
				0x7C,// XOP
				0x7D,// XSAVE
				0x7E,// XSAVEC
				0x7F,// XSAVEOPT
				0x80,// XSAVES
				0x81,// SEV_SNP
				0x82,// SERIALIZE
				0x83,// TSXLDTRK
				0x84,// INVLPGB
				0x85,// AMX_BF16
				0x86,// AMX_TILE
				0x87,// AMX_INT8
				0x88,// CENTAUR_AIS
				0x89,// MOV_TR
				0x8A,// SMM
				0x8B,// TDX
				0x8C,// KL
				0x8D,// AESKLE
				0x8D, 0x8E,// AESKLE_and_WIDE_KL
				0x8F,// UINTR
				0x90,// HRESET
				0x91,// AVX_VNNI
				0x92,// FRED
				0x93,// LKGS
				0x94,// AVX512_FP16
				0x21, 0x94,// AVX512VL_and_AVX512_FP16
				0x95,// UDBG
				0x96,// KNC
				0x97,// PADLOCK_UNDOC
			};
	}
}
#endif
