// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if INSTR_INFO
namespace Blazed.Intel.InstructionInfoInternal {
	static partial class CpuidFeatureInternalData {
		static System.ReadOnlySpan<byte> GetGetCpuidFeaturesData() =>
			new byte[] {
				// Header
				0x00,
				0x00,
				0x01,
				0x80,
				0xFD,
				0x3F,
				0x00,
				0x00,
				0x10,
				0x70,
				0x00,
				0x00,
				0x04,
				0x00,
				0x00,
				0x04,
				0x60,
				0x1B,
				0x00,
				0x00,
				0x02,
				0x01,

				0x00,// INTEL8086
				0x01,// INTEL8086_ONLY
				0x02,// INTEL186
				0x03,// INTEL286
				0x04,// INTEL286_ONLY
				0x05,// INTEL386
				0x06,// INTEL386_ONLY
				0x07,// INTEL386_A0_ONLY
				0x08,// INTEL486
				0x09,// INTEL486_A_ONLY
				0x0A,// UMOV
				0x0B,// IA64
				0x0C,// X64
				0x0D,// ADX
				0x0E,// AES
				0x0F,// AVX
				0x0E, 0x0F,// AES_and_AVX
				0x10,// AVX2
				0x11,// AVX512_4FMAPS
				0x12,// AVX512_4VNNIW
				0x14,// AVX512_BITALG
				0x15,// AVX512_IFMA
				0x16,// AVX512_VBMI
				0x17,// AVX512_VBMI2
				0x18,// AVX512_VNNI
				0x1A,// AVX512_VPOPCNTDQ
				0x1B,// AVX512BW
				0x1C,// AVX512CD
				0x1D,// AVX512DQ
				0x1E,// AVX512ER
				0x1F,// AVX512F
				0x1F, 0x13,// AVX512F_and_AVX512_BF16
				0x1F, 0x19,// AVX512F_and_AVX512_VP2INTERSECT
				0x20,// AVX512PF
				0x21, 0x13,// AVX512VL_and_AVX512_BF16
				0x21, 0x14,// AVX512VL_and_AVX512_BITALG
				0x21, 0x15,// AVX512VL_and_AVX512_IFMA
				0x21, 0x16,// AVX512VL_and_AVX512_VBMI
				0x21, 0x17,// AVX512VL_and_AVX512_VBMI2
				0x21, 0x18,// AVX512VL_and_AVX512_VNNI
				0x21, 0x19,// AVX512VL_and_AVX512_VP2INTERSECT
				0x21, 0x1A,// AVX512VL_and_AVX512_VPOPCNTDQ
				0x21, 0x1B,// AVX512VL_and_AVX512BW
				0x21, 0x1C,// AVX512VL_and_AVX512CD
				0x21, 0x1D,// AVX512VL_and_AVX512DQ
				0x21, 0x1F,// AVX512VL_and_AVX512F
				0x22,// BMI1
				0x23,// BMI2
				0x24,// CET_IBT
				0x25,// CET_SS
				0x26,// CL1INVMB
				0x27,// CLDEMOTE
				0x28,// CLFLUSHOPT
				0x29,// CLFSH
				0x2A,// CLWB
				0x2B,// CLZERO
				0x2C,// CMOV
				0x2D,// CMPXCHG16B
				0x2E,// CPUID
				0x2F,// CX8
				0x30,// D3NOW
				0x31,// D3NOWEXT
				0x32,// OSS
				0x33,// ENQCMD
				0x34,// F16C
				0x35,// FMA
				0x36,// FMA4
				0x37,// FPU
				0x37, 0x2C,// FPU_and_CMOV
				0x38,// FPU287
				0x39,// FPU287XL_ONLY
				0x3A,// FPU387
				0x3B,// FPU387SL_ONLY
				0x3C,// FSGSBASE
				0x3D,// FXSR
				0x3E,// GFNI
				0x0F, 0x3E,// AVX_and_GFNI
				0x1F, 0x3E,// AVX512F_and_GFNI
				0x21, 0x3E,// AVX512VL_and_GFNI
				0x40,// HLE_or_RTM
				0x42,// INVPCID
				0x44,// LWP
				0x45,// LZCNT
				0x46,// MCOMMIT
				0x47,// MMX
				0x48,// MONITOR
				0x49,// MONITORX
				0x4A,// MOVBE
				0x4B,// MOVDIR64B
				0x4C,// MOVDIRI
				0x4D,// MPX
				0x4E,// MSR
				0x4F,// MULTIBYTENOP
				0x50,// PADLOCK_ACE
				0x51,// PADLOCK_PHE
				0x52,// PADLOCK_PMM
				0x53,// PAUSE
				0x54,// PCLMULQDQ
				0x54, 0x0F,// PCLMULQDQ_and_AVX
				0x55,// PCOMMIT
				0x56,// PCONFIG
				0x57,// PKU
				0x58,// POPCNT
				0x59,// PREFETCHW
				0x5A,// PREFETCHWT1
				0x5B,// PTWRITE
				0x5C,// RDPID
				0x5D,// RDPMC
				0x5E,// RDPRU
				0x5F,// RDRAND
				0x60,// RDSEED
				0x61,// RDTSCP
				0x62,// RTM
				0x63,// SEP
				0x64,// SGX1
				0x65,// SHA
				0x67,// SKINIT_or_SVM
				0x68,// SMAP
				0x69,// SMX
				0x6A,// SSE
				0x6B,// SSE2
				0x6C,// SSE3
				0x37, 0x6C,// FPU_and_SSE3
				0x6D,// SSE4_1
				0x6E,// SSE4_2
				0x6F,// SSE4A
				0x70,// SSSE3
				0x71,// SVM
				0x72,// SEV_ES
				0x73,// SYSCALL
				0x74,// TBM
				0x75,// TSC
				0x76,// VAES
				0x1F, 0x76,// AVX512F_and_VAES
				0x21, 0x76,// AVX512VL_and_VAES
				0x77,// VMX
				0x77, 0x41,// VMX_and_INVEPT
				0x77, 0x43,// VMX_and_INVVPID
				0x78,// VPCLMULQDQ
				0x1F, 0x78,// AVX512F_and_VPCLMULQDQ
				0x21, 0x78,// AVX512VL_and_VPCLMULQDQ
				0x79,// WAITPKG
				0x7A,// WBNOINVD
				0x7B,// XOP
				0x7C,// XSAVE
				0x7D,// XSAVEC
				0x7E,// XSAVEOPT
				0x7F,// XSAVES
				0x80,// SEV_SNP
				0x81,// SERIALIZE
				0x82,// TSXLDTRK
				0x83,// INVLPGB
				0x84,// AMX_BF16
				0x85,// AMX_TILE
				0x86,// AMX_INT8
				0x87,// CENTAUR_AIS
				0x88,// MOV_TR
				0x89,// SMM
				0x8A,// TDX
				0x8B,// KL
				0x8C,// AESKLE
				0x8C, 0x8D,// AESKLE_and_WIDE_KL
				0x8E,// UINTR
				0x8F,// HRESET
				0x90,// AVX_VNNI
				0x91,// FRED
				0x92,// LKGS
				0x93,// AVX512_FP16
				0x21, 0x93,// AVX512VL_and_AVX512_FP16
				0x94,// UDBG
				0x95,// KNC
				0x96,// PADLOCK_UNDOC
			};
	}
}
#endif
