// SPDX-License-Identifier: MIT
// Copyright (C) 2018-present iced project and contributors

// ⚠️This file was generated by GENERATOR!🦹‍♂️

#nullable enable

#if NASM
namespace Blazed.Intel.NasmFormatterInternal {
	enum SizeOverride {
		None,
		Size16,
		Size32,
		Size64,
	}
}
#endif
