name: GitHub CI
on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "build-dotnet"
      - "src/**"
      - "!**/*.md"
    branches:
      - master
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "build-dotnet"
      - "src/**"
      - "!**/*.md"
    branches:
      - master

# Keep this in sync with the other *.yml files
env:
  CI_REQ_DOTNET_SDK_VER: '6.0.x'

jobs:

  build-dotnet:
    name: C# (${{matrix.os}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}

      - name: Build and test
        shell: bash
        run: ./build-dotnet

      - uses: actions/upload-artifact@v3
        with:
          name: coverage.info
          path: src/csharp/Iced.UnitTests/coverage.info
          if-no-files-found: error

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: src/csharp/Iced.UnitTests/coverage.info
