# This is triggered when a new release is created (using the GitHub UI)
name: New Release
on:
  release:
    types: [released]

# Keep this in sync with the other *.yml files
env:
  CI_REQ_DOTNET_SDK_VER: '6.0.x'

jobs:

  #############################################################################
  #############################################################################
  #############################################################################

  build-dotnet:
    name: C# (${{matrix.os}})
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}

      - name: Build and test
        shell: bash
        run: |
          extra_args=
          if [[ "$OSTYPE" != "linux-gnu"* ]]; then
            extra_args=--quick-check
          fi
          ./build-dotnet $extra_args

  #############################################################################
  #############################################################################
  #############################################################################

  upload-files:
    runs-on: ubuntu-latest
    name: Upload files
    needs:
      - build-dotnet

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.CI_REQ_DOTNET_SDK_VER}}

      - uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts